apiVersion: v1
kind: Service
metadata:
  name: polar-config
  labels:
    app: polar-config
spec:
  type: ClusterIP
  selector:
    app: polar-config
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888